#项目公共配置属性配置
spring:
#编码设置
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  messages:
    encoding: utf-8

#freemark设置
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

server:
  tomcat:
    uri-encoding: utf-8