#生产环境配置
debug: false   #控制项目中某些debug信息的输出
spring:
  jpa:
    #执行时输出sql
    show-sql: true
    #hibernate建表机制
    hibernate:
      ddl-auto: update
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/gopandas_dev;DB_CLOSE_DELAY=-1
    username: sa
    password: 123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,log4j
    logSlowSql: true
h2server:
  open2Server: true